-- Run this once in Supabase SQL Editor. The table is intentionally not
-- readable from the browser: Netlify Functions use the service-role key.
create table if not exists public.user_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_key text not null,
  status text not null check (status in ('active', 'revoked')),
  stripe_customer_id text,
  stripe_checkout_session_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_key)
);

alter table public.user_entitlements enable row level security;

-- Do not create browser policies here. Only the server can read or write
-- entitlements, which prevents customers from editing their own access.

-- Create a private bucket in Storage named "course-modules". Do not make it
-- public and do not add public read policies for it.
